### ISSUE TITLE
API wepy.request is not a Promise

### ISSUE THREAD

**Issue by pinguo-weihaodong** [wepyjs/wepy-wechat-demo#13]
When I use wepy.request, it throws this error:
> Cannot read property 'then' of undefined;at App lifeCycleMethod onLaunch function

**Comment by Gcaufy** [comment]
```
this.use('promisify');
```

https://github.com/Tencent/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8async-await
