### ISSUE TITLE
tab 的问题，

### ISSUE THREAD

**Issue by mrpeng** [wepyjs/wepy-wechat-demo#18]
我在本地调试，tab能切换过去，远程调试也可以，但预览的话，tab就切换不了页面了，这是什么原因？

**Comment by Gcaufy** [comment]
打开调试模式看看是否有报错。
或者远程调试一下试试看看

**Comment by mrpeng** [comment]
原来是项目设置的问题，
把
上传代码时样式自动补全
代码上传时自动压缩
去掉了，然后再预览就没有问题了。
但是有个别的问题，右侧的滚动条，到最底下时，到了tab的底，应该在tab之上就好了。
