### ISSUE TITLE
为什么启动的时候找不到

### ISSUE THREAD

**Issue by kiner-tang** [wepyjs/wepy-wechat-demo#3]
![image](https://cloud.githubusercontent.com/assets/10286961/21922378/3b21d8a0-d9a9-11e6-8e3d-75d64a641772.png)
![image](https://cloud.githubusercontent.com/assets/10286961/21922392/49c9ae0a-d9a9-11e6-97ea-8a95809e37ee.png)

**Comment by Gcaufy** [comment]
没有执行`npm install`
