### ISSUE TITLE
全局文件 App.jason 呢？ 

### ISSUE THREAD

**Issue by leonmax120** [wepyjs/wepy-wechat-demo#5]
请问是不是没有上传全局控制文件app.jason ?

**Comment by Gcaufy** [comment]
DEMO不能运行起来？还是怎么样？

**Comment by leonmax120** [comment]
对啊 不能运行 我看了看demo基本上都需要app.jason 这个全局。 您看这个 

![image](https://cloud.githubusercontent.com/assets/1075937/21970010/ca667738-dbf6-11e6-84d7-d68e7e300d16.png)

**Comment by Gcaufy** [comment]
demo是肯定可以运行的。不能运行只可能有这几种原因。
1. 未执行编译命令
2. 编译命令出去
3. 开发者工具选择的不是dist目录。
