### ISSUE TITLE
请问，wepy框架是如何打断点调试的？

### ISSUE THREAD

**Issue by Sher9** [wepyjs/wepy-wechat-demo#6]
如题。
微信小程序开发工具打开的打包后的文件。
如果我想断点看js里面的值，请问如何操作的呢？

**Comment by Gcaufy** [comment]
暂时没有支持SourceMap功能，不开uglifyjs插件的话，还是一样的调试，生成的ES5代码并不会有很大的阅读障碍。

**Comment by Gcaufy** [comment]
已支持sourceMap.
