### ISSUE TITLE
网络请求无法超过10次？

### ISSUE THREAD

**Issue by moersing** [wepyjs/wepy-wechat-demo#9]
![image](https://cloud.githubusercontent.com/assets/12471233/23735006/e776d864-04bd-11e7-9cf9-5927caf649a9.png)

点击demo页面的`点我发起10次` 请求。

**Comment by Gcaufy** [comment]
这个功能一直都存在，demo中的确是有一点问题，参考我刚才的commit在app.wpy中加一句
```
    constructor () {
         super();
         this.use('requestfix');
     };
```
然后使用`wepy.request` 就好了。

PS: issue 提错了地方

**Comment by moersing** [comment]
不好意思，提错位置了。
